import 'Atom.dart';
import 'package:vector_math/vector_math_64.dart' as vector_math;

class Atoms {
  static Map<String, Atom> atomsList = {
    'hydrogen': Atom(
      id: 1,
      name: "Hydrogen",
      group: "Alkali metal",
      symbol: "H",
      atomicNumber: 1,
      numberOfNeutrons: 0,
      mass: 1.008,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'helium': Atom(
      id: 2,
      name: "Helium",
      group: "Noble gas",
      symbol: "He",
      atomicNumber: 2,
      numberOfNeutrons: 2,
      mass: 4.0026,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'lithium': Atom(
      id: 3,
      name: "Lithium",
      group: "Alkali metal",
      symbol: "Li",
      atomicNumber: 3,
      numberOfNeutrons: 4,
      mass: 6.94,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'beryllium': Atom(
      id: 4,
      name: "Beryllium",
      group: "Alkaline earth metal",
      symbol: "Be",
      atomicNumber: 4,
      numberOfNeutrons: 5,
      mass: 9.0122,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'boron': Atom(
      id: 5,
      name: "Boron",
      group: "Metalloid",
      symbol: "B",
      atomicNumber: 5,
      numberOfNeutrons: 6,
      mass: 10.81,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'carbon': Atom(
      id: 6,
      name: "Carbon",
      group: "Group 14",
      symbol: "C",
      atomicNumber: 6,
      numberOfNeutrons: 6,
      mass: 12.01,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'nitrogen': Atom(
      id: 7,
      name: "Nitrogen",
      group: "Group 15",
      symbol: "N",
      atomicNumber: 7,
      numberOfNeutrons: 7,
      mass: 14.01,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 3),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'oxygen': Atom(
      id: 8,
      name: "Oxygen",
      group: "Group 16",
      symbol: "O",
      atomicNumber: 8,
      numberOfNeutrons: 8,
      mass: 16.00,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 4),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'fluorine': Atom(
      id: 9,
      name: "Fluorine",
      group: "Group 17",
      symbol: "F",
      atomicNumber: 9,
      numberOfNeutrons: 10,
      mass: 19.00,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 5),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'neon': Atom(
      id: 10,
      name: "Neon",
      group: "Noble gas",
      symbol: "Ne",
      atomicNumber: 10,
      numberOfNeutrons: 10,
      mass: 20.18,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'sodium': Atom(
      id: 11,
      name: "Sodium",
      group: "Alkali metal",
      symbol: "Na",
      atomicNumber: 11,
      numberOfNeutrons: 12,
      mass: 22.99,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'magnesium': Atom(
      id: 12,
      name: "Magnesium",
      group: "Alkaline earth metal",
      symbol: "Mg",
      atomicNumber: 12,
      numberOfNeutrons: 12,
      mass: 24.31,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'aluminum': Atom(
      id: 13,
      name: "Aluminum",
      group: "Post-transition metal",
      symbol: "Al",
      atomicNumber: 13,
      numberOfNeutrons: 14,
      mass: 26.98,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'silicon': Atom(
      id: 14,
      name: "Silicon",
      group: "Metalloid",
      symbol: "Si",
      atomicNumber: 14,
      numberOfNeutrons: 14,
      mass: 28.09,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'phosphorus': Atom(
      id: 15,
      name: "Phosphorus",
      group: "Non-metal",
      symbol: "P",
      atomicNumber: 15,
      numberOfNeutrons: 16,
      mass: 30.97,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 3),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'sulfur': Atom(
      id: 16,
      name: "Sulfur",
      group: "Non-metal",
      symbol: "S",
      atomicNumber: 16,
      numberOfNeutrons: 16,
      mass: 32.07,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 4),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'chlorine': Atom(
      id: 17,
      name: "Chlorine",
      group: "Halogens",
      symbol: "Cl",
      atomicNumber: 17,
      numberOfNeutrons: 18,
      mass: 35.45,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 5),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'argon': Atom(
      id: 18,
      name: "Argon",
      group: "Noble gases",
      symbol: "Ar",
      atomicNumber: 18,
      numberOfNeutrons: 22,
      mass: 39.95,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'potassium': Atom(
      id: 19,
      name: "Potassium",
      group: "Alkali metal",
      symbol: "K",
      atomicNumber: 19,
      numberOfNeutrons: 20,
      mass: 39.10,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'calcium': Atom(
      id: 20,
      name: "Calcium",
      group: "Alkaline earth metal",
      symbol: "Ca",
      atomicNumber: 20,
      numberOfNeutrons: 20,
      mass: 40.08,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'scandium': Atom(
      id: 21,
      name: "Scandium",
      group: "Transition metal",
      symbol: "Sc",
      atomicNumber: 21,
      numberOfNeutrons: 24,
      mass: 44.96,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'titanium': Atom(
      id: 22,
      name: "Titanium",
      group: "Transition metal",
      symbol: "Ti",
      atomicNumber: 22,
      numberOfNeutrons: 26,
      mass: 47.87,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'vanadium': Atom(
      id: 23,
      name: "Vanadium",
      group: "Transition metal",
      symbol: "V",
      atomicNumber: 23,
      numberOfNeutrons: 28,
      mass: 50.94,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 3),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'chromium': Atom(
      id: 24,
      name: "Chromium",
      group: "Transition metal",
      symbol: "Cr",
      atomicNumber: 24,
      numberOfNeutrons: 28,
      mass: 51.996,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 1),
          Orbital(type: '3d', occupancy: 5),
          Orbital(type: '4s', occupancy: 1),
          Orbital(type: '3d', occupancy: 5),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),

    'yttrium': Atom(
      id: 39,
      name: "Yttrium",
      group: "Transition metal",
      symbol: "Y",
      atomicNumber: 39,
      numberOfNeutrons: 50,
      mass: 88.91,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 2),
          Orbital(type: '4d', occupancy: 1),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'zirconium': Atom(
      id: 40,
      name: "Zirconium",
      group: "Transition metal",
      symbol: "Zr",
      atomicNumber: 40,
      numberOfNeutrons: 51,
      mass: 91.22,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 2),
          Orbital(type: '4d', occupancy: 2),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'niobium': Atom(
      id: 41,
      name: "Niobium",
      group: "Transition metal",
      symbol: "Nb",
      atomicNumber: 41,
      numberOfNeutrons: 52,
      mass: 92.91,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 1),
          Orbital(type: '4d', occupancy: 4),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'molybdenum': Atom(
      id: 42,
      name: "Molybdenum",
      group: "Transition metal",
      symbol: "Mo",
      atomicNumber: 42,
      numberOfNeutrons: 54,
      mass: 95.95,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 1),
          Orbital(type: '4d', occupancy: 5),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),

    'iridium': Atom(
      id: 77,
      name: "Iridium",
      group: "Transition metal",
      symbol: "Ir",
      atomicNumber: 77,
      numberOfNeutrons: 115,
      mass: 192.22,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 2),
          Orbital(type: '4d', occupancy: 10),
          Orbital(type: '5p', occupancy: 6),
          Orbital(type: '6s', occupancy: 2),
          Orbital(type: '4f', occupancy: 14),
          Orbital(type: '5d', occupancy: 9),
          Orbital(type: '6p', occupancy: 0),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'platinum': Atom(
      id: 78,
      name: "Platinum",
      group: "Transition metal",
      symbol: "Pt",
      atomicNumber: 78,
      numberOfNeutrons: 117,
      mass: 195.08,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 2),
          Orbital(type: '4d', occupancy: 10),
          Orbital(type: '5p', occupancy: 6),
          Orbital(type: '6s', occupancy: 2),
          Orbital(type: '4f', occupancy: 14),
          Orbital(type: '5d', occupancy: 10),
          Orbital(type: '6p', occupancy: 0),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'gold': Atom(
      id: 79,
      name: "Gold",
      group: "Transition metal",
      symbol: "Au",
      atomicNumber: 79,
      numberOfNeutrons: 118,
      mass: 196.97,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 2),
          Orbital(type: '4d', occupancy: 10),
          Orbital(type: '5p', occupancy: 6),
          Orbital(type: '6s', occupancy: 1),
          Orbital(type: '4f', occupancy: 14),
          Orbital(type: '5d', occupancy: 10),
          Orbital(type: '6p', occupancy: 0),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
    'mercury': Atom(
      id: 80,
      name: "Mercury",
      group: "Post-transition metal",
      symbol: "Hg",
      atomicNumber: 80,
      numberOfNeutrons: 121,
      mass: 200.59,
      electronConfiguration: ElectronConfiguration(
        orbitals: [
          Orbital(type: '1s', occupancy: 2),
          Orbital(type: '2s', occupancy: 2),
          Orbital(type: '2p', occupancy: 6),
          Orbital(type: '3s', occupancy: 2),
          Orbital(type: '3p', occupancy: 6),
          Orbital(type: '4s', occupancy: 2),
          Orbital(type: '3d', occupancy: 10),
          Orbital(type: '4p', occupancy: 6),
          Orbital(type: '5s', occupancy: 2),
          Orbital(type: '4d', occupancy: 10),
          Orbital(type: '5p', occupancy: 6),
          Orbital(type: '6s', occupancy: 2),
          Orbital(type: '4f', occupancy: 14),
          Orbital(type: '5d', occupancy: 10),
          Orbital(type: '6p', occupancy: 0),
        ],
      ),
      position: vector_math.Vector3(0.0, 0.0, 0.0),
      velocity: vector_math.Vector3(0.0, 0.0, 0.0),
    ),
  };
}